// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5sjmq1QUNYbRpM9gy16Xwf7np47IkVQM',
    appId: '1:655396027836:web:7fe8f7f93433220ef3ffb9',
    messagingSenderId: '655396027836',
    projectId: 'smart-in-policy',
    authDomain: 'smart-in-policy.firebaseapp.com',
    storageBucket: 'smart-in-policy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv8A632HxqWlQFn2zxI4nbavhCAEK787E',
    appId: '1:655396027836:android:fb0d197661c20c37f3ffb9',
    messagingSenderId: '655396027836',
    projectId: 'smart-in-policy',
    storageBucket: 'smart-in-policy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnQUaDwk3PV7T1xx3maKCZRfL8yhJfxaw',
    appId: '1:655396027836:ios:a774838dee1ec898f3ffb9',
    messagingSenderId: '655396027836',
    projectId: 'smart-in-policy',
    storageBucket: 'smart-in-policy.appspot.com',
    iosClientId: '655396027836-kss32p50jvhun0vpfght8j28cf0ikp2f.apps.googleusercontent.com',
    iosBundleId: 'dev.khanin.smartinpolicy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnQUaDwk3PV7T1xx3maKCZRfL8yhJfxaw',
    appId: '1:655396027836:ios:f1af185b876a4bb7f3ffb9',
    messagingSenderId: '655396027836',
    projectId: 'smart-in-policy',
    storageBucket: 'smart-in-policy.appspot.com',
    iosClientId: '655396027836-uvf9a09e9s7qpeap13unefh3u4tshgd7.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartInPolicy.RunnerTests',
  );
}
